package com.example.lianxi.green;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.lianxi.Goods;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GOODS".
*/
public class GoodsDao extends AbstractDao<Goods, Long> {

    public static final String TABLENAME = "GOODS";

    /**
     * Properties of entity Goods.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Title = new Property(0, String.class, "title", false, "TITLE");
        public final static Property BargainPrice = new Property(1, double.class, "bargainPrice", false, "BARGAIN_PRICE");
        public final static Property Images = new Property(2, String.class, "images", false, "IMAGES");
        public final static Property Pid = new Property(3, long.class, "pid", true, "_id");
        public final static Property Price = new Property(4, String.class, "price", false, "PRICE");
    }


    public GoodsDao(DaoConfig config) {
        super(config);
    }
    
    public GoodsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOODS\" (" + //
                "\"TITLE\" TEXT," + // 0: title
                "\"BARGAIN_PRICE\" REAL NOT NULL ," + // 1: bargainPrice
                "\"IMAGES\" TEXT," + // 2: images
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 3: pid
                "\"PRICE\" TEXT);"); // 4: price
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOODS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Goods entity) {
        stmt.clearBindings();
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(1, title);
        }
        stmt.bindDouble(2, entity.getBargainPrice());
 
        String images = entity.getImages();
        if (images != null) {
            stmt.bindString(3, images);
        }
        stmt.bindLong(4, entity.getPid());
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(5, price);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Goods entity) {
        stmt.clearBindings();
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(1, title);
        }
        stmt.bindDouble(2, entity.getBargainPrice());
 
        String images = entity.getImages();
        if (images != null) {
            stmt.bindString(3, images);
        }
        stmt.bindLong(4, entity.getPid());
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(5, price);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 3);
    }    

    @Override
    public Goods readEntity(Cursor cursor, int offset) {
        Goods entity = new Goods( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // title
            cursor.getDouble(offset + 1), // bargainPrice
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // images
            cursor.getLong(offset + 3), // pid
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // price
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Goods entity, int offset) {
        entity.setTitle(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBargainPrice(cursor.getDouble(offset + 1));
        entity.setImages(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPid(cursor.getLong(offset + 3));
        entity.setPrice(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Goods entity, long rowId) {
        entity.setPid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Goods entity) {
        if(entity != null) {
            return entity.getPid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Goods entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
